// dropdownOptions.ts

export const cities = [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'San Francisco',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Washington',
    'Boston',
    'El Paso',
    'Nashville',
    'Detroit',
    'Oklahoma City',
    'Portland',
    'Las Vegas',
    'Memphis',
    'Louisville',
    'Baltimore',
    'Milwaukee',
    'Albuquerque',
    'Tucson',
    'Fresno',
    'Sacramento',
    'Kansas City',
    'Mesa',
    'Atlanta',
    'Omaha',
    'Colorado Springs'
  ];
  
  export const states = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming'
  ];
  
  export const countries = [
    'United States',
    'Canada',
    'Mexico',
    'United Kingdom',
    'Germany',
    'France',
    'Italy',
    'Spain',
    'Australia',
    'India',
    'China',
    'Japan',
    'South Korea',
    'Brazil',
    'Argentina',
    'Chile',
    'Colombia',
    'Peru',
    'Russia',
    'Ukraine',
    'Poland',
    'Netherlands',
    'Belgium',
    'Sweden',
    'Norway',
    'Denmark',
    'Finland',
    'Ireland',
    'Portugal',
    'Greece',
    'Turkey',
    'South Africa',
    'Egypt',
    'Saudi Arabia',
    'United Arab Emirates',
    'Israel',
    'Singapore',
    'Malaysia',
    'Thailand',
    'Vietnam',
    'Philippines',
    'Indonesia',
    'New Zealand',
    'Switzerland',
    'Austria',
    'Hungary',
    'Czech Republic',
    'Romania',
    'Bulgaria',
    'Croatia',
    'Slovenia'
  ];
  
  export const zipCodes = [
    '10001',
    '90001',
    '60601',
    '77001',
    '85001',
    '19101',
    '78201',
    '92101',
    '75201',
    '95101',
    '73301',
    '32099',
    '76101',
    '43201',
    '28201',
    '94101',
    '46201',
    '98101',
    '80201',
    '20001',
    '02201',
    '79901',
    '37201',
    '48201',
    '73101',
    '97201',
    '89101',
    '38101',
    '40201',
    '21201',
    '53201',
    '87101',
    '85701',
    '93701',
    '95801',
    '64101',
    '85201',
    '30301',
    '68101',
    '80901'
  ];
  
  export {};
  
  